[workspace]
members = [
    ".",
    "example",
]

[package]
name = "axum_database_sessions"
version = "6.0.0"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "Library to Provide Database Session management layer."
edition = "2021"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/axum_database_sessions"
keywords = ["Axum", "Tower", "SQLx", "Session"]
repository = "https://github.com/AscendingCreations/AxumSessions"

[features]
default = ["postgres-rustls"]
sqlite-rustls = ["sqlx/sqlite", "sqlx/runtime-tokio-rustls"]
sqlite-native = ["sqlx/sqlite", "sqlx/runtime-tokio-native-tls"]
postgres-rustls = ["sqlx/postgres", "sqlx/runtime-tokio-rustls"]
postgres-native = ["sqlx/postgres", "sqlx/runtime-tokio-native-tls"]
mysql-rustls = ["sqlx/mysql", "sqlx/runtime-tokio-rustls"]
mysql-native = ["sqlx/mysql", "sqlx/runtime-tokio-native-tls"]
redis-db = ["redis"]

[dependencies]
axum-core = {version = "0.3.2"}
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
chrono = { version = "0.4.23", features = ["clock", "serde", "std"] }
tokio = { version = "1.25.0", features = ["full"] }
async-trait = "0.1.64"
tracing = "0.1.37"
thiserror = "1.0.38"
http-body = "0.4.5"
uuid = { version = "1.3.0", features = ["v4", "serde"] }
http = "0.2.9"
tower-layer = "0.3.2"
tower-service = "0.3.2"
sqlx = { version = "0.6.2", default-features = false, features = [
    "chrono",
    "uuid",
], optional = true }
cookie = { version = "0.17.0", features = ["percent-encode", "private"] }
futures = "0.3.26"
bytes = "1.4.0"
dashmap = "5.4.0"
redis = { version = "0.22.3", features = ["tokio-comp"], optional = true }

[dev-dependencies]
axum = { version = "0.6.7", features = ["macros"]}
hyper = "0.14.24"
tower = "0.4.13"
log = { version = "0.4.17", default-features = false }