[workspace]
members = [
    ".",
    "examples/postgres",
    "examples/redis",
    "examples/surrealdb",
]

[package]
name = "axum_session"
version = "0.2.3"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "Memory and/or Database Session management layer for axum."
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/axum_session"
keywords = ["Axum", "Tower", "SQLx", "Session", "surrealdb"]
repository = "https://github.com/AscendingCreations/AxumSessions"

[features]
default = ["postgres-rustls", "sqlite-rustls", "mysql-rustls", "redis-db", "surrealdb-mem"]

sqlite-rustls = ["sqlx/sqlite", "sqlx/tls-rustls"]
sqlite-native = ["sqlx/sqlite", "sqlx/tls-native-tls"]
postgres-rustls = ["sqlx/postgres", "sqlx/tls-rustls"]
postgres-native = ["sqlx/postgres", "sqlx/tls-native-tls"]
mysql-rustls = ["sqlx/mysql", "sqlx/tls-rustls"]
mysql-native = ["sqlx/mysql", "sqlx/tls-native-tls"]
redis-db = ["redis"]
surrealdb-rocksdb =  ["surrealdb/kv-rocksdb", "surrealdb_tag"]
surrealdb-tikv =  ["surrealdb/kv-tikv", "surrealdb_tag"]
surrealdb-indxdb =  ["surrealdb/kv-indxdb", "surrealdb_tag"]
surrealdb-fdb-5_1 =  ["surrealdb/kv-fdb-5_1", "surrealdb_tag"]
surrealdb-fdb-5_2 =  ["surrealdb/kv-fdb-5_2", "surrealdb_tag"]
surrealdb-fdb-6_0 =  ["surrealdb/kv-fdb-6_0", "surrealdb_tag"]
surrealdb-fdb-6_1 =  ["surrealdb/kv-fdb-6_1", "surrealdb_tag"]
surrealdb-fdb-6_2 =  ["surrealdb/kv-fdb-6_2", "surrealdb_tag"]
surrealdb-fdb-6_3 =  ["surrealdb/kv-fdb-6_3", "surrealdb_tag"]
surrealdb-fdb-7_0 =  ["surrealdb/kv-fdb-7_0", "surrealdb_tag"]
surrealdb-fdb-7_1 =  ["surrealdb/kv-fdb-7_1", "surrealdb_tag"]
surrealdb-mem =  ["surrealdb/kv-mem", "surrealdb_tag"]

#private features.
surrealdb_tag = []

[dependencies]
axum-core = {version = "0.3.4"}
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
chrono = { version = "0.4.24", default-features = false, features = ["clock", "serde", "std"] }
tokio = { version = "1.28.1", features = ["full"] }
async-trait = "0.1.68"
tracing = "0.1.37"
thiserror = "1.0.40"
http-body = "0.4.5"
uuid = { version = "1.3.3", features = ["v4", "serde"] }
http = "0.2.9"
tower-layer = "0.3.2"
tower-service = "0.3.2"
sqlx = { version = "=0.7.0", default-features = false, features = [
    "runtime-tokio",
    "chrono",
    "uuid",
], optional = true }
cookie = { version = "0.17.0", features = ["percent-encode", "private"] }
futures = "0.3.28"
bytes = "1.4.0"
dashmap = "5.4.0"
redis = { version = "0.23.0", features = ["tokio-comp"], optional = true }
surrealdb = { version = "1.0.0-beta.9", optional = true }
aes-gcm = { version = "0.10.1"}
base64 = { version = "0.21.0"}
rand = { version = "0.8.5"}
fastbloom-rs = "0.5.3"

[dev-dependencies]
axum = { version = "0.6.18", features = ["macros"]}
hyper = "0.14.26"
tower = "0.4.13"
log = { version = "0.4.17", default-features = false }

[package.metadata.docs.rs]
features = ["sqlite-rustls","mysql-rustls","redis-db", "surrealdb-rocksdb", "surrealdb-mem"]
rustdoc-args = ["--document-private-items"]
