[package]
name = "axum_database_sessions"
version = "4.0.2"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "Library to Provide Database Session management layer."
edition = "2021"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/axum_database_sessions"
keywords = ["Axum", "Tower", "SQLx", "Session"]
repository = "https://github.com/AscendingCreations/AxumSessions"

[features]
default = ["postgres-rustls"]
sqlite-rustls = ["sqlx/sqlite", "sqlx/runtime-tokio-rustls"]
sqlite-native = ["sqlx/sqlite", "sqlx/runtime-tokio-native-tls"]
postgres-rustls = ["sqlx/postgres", "sqlx/runtime-tokio-rustls"]
postgres-native = ["sqlx/postgres", "sqlx/runtime-tokio-native-tls"]
mysql-rustls = ["sqlx/mysql", "sqlx/runtime-tokio-rustls"]
mysql-native = ["sqlx/mysql", "sqlx/runtime-tokio-native-tls"]
redis-db = ["redis"]

[dependencies]
axum-core = "0.2.7"
serde = { version = "1.0.142", features = ["derive"] }
serde_json = "1.0.83"
chrono = { version = "0.4.20", features = ["clock", "serde", "std"] }
tokio = { version = "1.20.1", features = ["full"] }
async-trait = "0.1.57"
tracing = "0.1.36"
thiserror = "1.0.32"
http-body = "0.4.5"
uuid = { version = "1.1.2", features = ["v4", "serde"] }
http = "0.2.8"
tower-layer = "0.3.1"
tower-service = "0.3.2"
sqlx = { version = "0.6.1", default-features = false, features = [
    "chrono",
    "uuid",
], optional = true }
cookie = { version = "0.16.0", features = ["percent-encode", "private"] }
futures = "0.3.21"
bytes = "1.2.1"
dashmap = "5.3.4"
redis = { version = "0.21.5", features = ["tokio-comp"], optional = true }

[dev-dependencies]
anyhow = "1.0.60"
axum = "0.5.13"

