[package]
name = "surreal"
version = "0.0.1"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
edition = "2021"

[dependencies]
axum = {version = "0.6.12"}
tokio = { version = "1.22.0", features = ["full", "tracing"] }
async-trait = "0.1.58"
axum_session = { path = "../../", features = [ "surrealdb-mem"] }
surrealdb = { version = "1.0.0-beta.9" , features = ["kv-mem"]}