name: AxumSessions

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  MSRV: '1.60'

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: stable

      - run: cargo fmt --all -- --check

  check:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          databases: [key-store]

      steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@master
          with:
            components: clippy
            toolchain: nightly

        - uses: Swatinem/rust-cache@v2
          with:
            key: ${{ matrix.databases }}

        - name: Check
          run: cargo clippy --features ${{ matrix.databases }}

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          profile: minimal
          toolchain: nightly

      - run: |
        
      - name: Migrate database
        run: |
          sudo apt-get install libpq-dev -y
      - name: Run Test
        run: cargo test  


